FROM node:19-alpine

WORKDIR /work
COPY package.json package-lock.json ./
RUN npm install
COPY ./ ./
RUN npm run build

FROM nginx:alpine
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
copy --from=0 /work/build /usr/share/nginx/html

